#!/usr/bin/python
# -*- coding:utf8 -*-

"""
Copyright (C) 2011 by lwp
levin108@gmail.com

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the
Free Software Foundation, Inc.,
51 Franklin Street, Suite 500, Boston, MA 02110-1335, USA.
"""

__revision__ = '0.2.0'

if __name__ == "__main__":
	from distutils.sysconfig import get_python_lib
	import os, sys
	lib_dir = get_python_lib()
	index = lib_dir.rfind('/')
	lib_dir = lib_dir[:index]
	site_dir = lib_dir + '/' + 'site-packages/'
	if os.path.exists(site_dir):
		sys.path.append(site_dir)
	site_dir += 'tweets2pdf/'
	if os.path.exists(site_dir):
		sys.path.append(site_dir)
	import tweets2pdf.tweets2pdf
	tweets2pdf.tweets2pdf.main()
